import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    user: null, // Will store user data like username
    isAuth: false, // Indicates if the user is authenticated
};

const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        // Action to handle user login
        loginSuccess: (state, action) => {
            state.user = action.payload; // Storing user info (e.g., username)
            state.isAuth = true; // Set authenticated to true
        },
        // Action to handle user logout
        logout: (state) => {
            state.user = null; // Clearing user data
            state.isAuth = false; // Set authenticated to false
        },
    },
});

// Exporting actions generated by createSlice
export const { loginSuccess, logout } = userSlice.actions;

// Exporting the reducer to be added to the store
export default userSlice.reducer;
